# Generated by Django 3.2.13 on 2022-06-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_table',
            name='content',
            field=models.TextField(),
        ),
    ]
