# Generated by Django 3.2.13 on 2022-06-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_alter_article_table_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_table',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
