# Generated by Django 3.2.13 on 2022-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('pswd', models.CharField(default=123, max_length=100)),
                ('rpswd', models.CharField(default=123, max_length=100)),
            ],
        ),
    ]
